config/routes.rb
Wallet::Application.routes.draw do

  namespace :admin do
    resources :sessions, only: [:create, :new, :destroy]
    resources :cards, only: [:index, :destroy]
  end

  get '/cookie-example' => 'cookie_example#index'

  resources :cards do
    collection do
      get 'expired'
    end
  end

  
  post '/share-card' => 'user_cards#create', as: 'share_card'

  resources :users do
    resources :cards
  end

  resources :sessions

  root "sessions#new"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
end

app/models/card.rb
class Card < ActiveRecord::Base
 validates_format_of :number, with: /\A[345]\d{11,15}\Z/
 validates :expiration_month, inclusion: {in: (1..12)}
 validates :expiration_year, inclusion: {in:(2015..2115)}
 validates :users, presence:true
 validate :not_expired

 def not_expired
   if self.expiration_date < Time.now
     errors.add(:expiration_date, 'Card has already expired')
   end
 end

 before_validation :set_expiration_date

 before_save :set_card_type

 def set_expiration_date
   self.expiration_date = DateTime.new(self.expiration_year,
                                       self.expiration_month,
                                       28)
 end

 scope :expired, lambda{ where('expiration_date < ?', Time.now) }

 def set_card_type
   first_num = self.number[0]
   self.card_type = case first_num
   when '3'
     'American Express'
   when '4'
     'Visa'
   when '5'
     'Mastercard'
   end
 end


 has_many :users, through: :user_cards
 has_many :user_cards
end

app/models/user.rb
class User < ActiveRecord::Base

  validates_presence_of :fname, :lname, :email, :password

  validates_uniqueness_of :email

  validates_confirmation_of :password

  validates_format_of :phone, with: /\d{3}-\d{3}-\d{4}/

  validates_numericality_of :balance, { greater_than_or_equal_to: 0 }

  has_many :user_cards
  has_many :cards, through: :user_cards

  before_destroy :destroy_solely_owned_cards

  def destroy_solely_owned_cards
    all_my_cards = self.cards
    owned_cards = all_my_cards.select do |card|
                    card.users.length == 1
                  end
    owned_cards.each &:destroy!
  end


  def full_name
    fname + ' ' + lname
  end
end

app/models/user_card.rb
class UserCard < ActiveRecord::Base
  belongs_to :user
  belongs_to :card
end

app/controllers/admin/cards_controller.rb
class Admin::CardsController < ApplicationController

  before_action :verify_admin

  def index
    @cards = Card.all
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy
    redirect_to admin_cards_path
  end

  private

  def verify_admin
    redirect_to root_path unless current_admin
  end

end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController

  def new
  end

  def create
    @admin = Admin.find_by_username( params[:username] )
    if @admin.present?
      if @admin.password == params[:password]
        session[:admin_id] = @admin.id
        redirect_to admin_cards_path
      else
        flash[:alert] = 'Wrong password'
        redirect_to new_admin_session_path
      end
    else
      flash[:alert] = 'No admin found with that username'
      redirect_to new_admin_session_path
    end
  end

  def destroy
    flash[:notice] = "#{current_admin.username} has Logged Out"
    session[:admin_id] = nil
    redirect_to root_path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include ApplicationHelper
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def index
   if params[:user_id].present?
      @user = User.find params[:user_id]
      @cards = @user.cards
      @header =  @user.fname + "'s Cards"
    else
      @cards = Card.all
      @header = "All Cards"
    end
  end

  def new
    @card = Card.new
  end

  def create
    @card = Card.new(card_params)
    @card.users << current_user

    if @card.valid?
      @card.save!
      redirect_to cards_path
    else
      flash[:alert] = "There was an error with your submission"
      render :new
    end
  end

  def show
    @card = Card.find(params[:id])
  end

  def expired
    @cards = Card.expired
    render :index
  end


  private

  def card_params
    params.require(:card).permit(:number,
                                 :expiration_month,
                                 :expiration_year)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    session[:user_id] = nil
  end

  def create
    user = User.find_by_email(params[:email])

    if user.password == params[:password]
        session[:user_id] = user.id
        flash[:notice] = "#{current_user.full_name} has logged in"
        redirect_to users_path
    else
      flash[:alert] = "Invalid Credentials"
      redirect_to new_session_path
    end
  end

  def destroy
    flash[:notice] = "#{current_user.full_name} has Logged Out"
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/user_cards_controller.rb
class UserCardsController < ApplicationController
  def create
    user = User.find user_card_params[:user_id]
    UserCard.create user_card_params
    redirect_to user_cards_path(user)
  end

  private

  def user_card_params
    params.require(:user_card).permit(:user_id, :card_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    redirect_to new_session_path unless current_user
    @users = User.all
  end

  def create
    @user = User.create user_params
    if @user.valid?
      flash[:notice] = "Thanks for signing up"
      session[:user_id] = @user.id
      redirect_to users_path
    else
      flash[:alert] = "There was a problem."
      render :new
    end
  end

  def show
    @user = User.find params[:id]
  end

  def edit
    @user = User.find params[:id]
  end

  def update

    @user = User.find params[:id]

    p = user_params

    if user_params[:password].blank?
      p.delete(:password)
      p.delete(:password_confirmation)
    end

    @user.update! p

    flash[:notice] = "Successful update"
    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find params[:id]
    @user.destroy!
    session.clear
    flash[:notice] = "Bye."
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:fname,
                                 :lname,
                                 :password,
                                 :email,
                                 :phone,
                                 :password_confirmation)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    if session[:user_id]
      current_user = User.find(session[:user_id])
    end
  end

  def current_admin
    if session[:admin_id]
      current_admin = Admin.find(session[:admin_id])
    end
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/cards/index.html.erb
<h2> Edit All User Cards </h2>

<hr>

<% @cards.each do |card| %>
  <%= render partial: 'cards/card', locals: { card: card } %>
  <%= link_to "Delete", admin_card_path(card), method: :delete %>
  <hr>
<% end %>

app/views/cards/_card.html.erb
<div class="<%= "card #{card.card_type.downcase.gsub(/\s/,'')}"%>" >
  <table class='card-attributes'>
    <tr>
      <td class ="label"> Name on Card:</td>
      <td> <%= card.users.map(&:full_name).join(', ') %> </td>
    </tr>
    <tr>
      <td> Card Type: </td>
      <td><%= link_to card.card_type, card_path(card) %> </td>
    </tr>
    <tr>
      <td> Card Number: </td>
      <td><%= card.number %> </td>
    </tr>
    <tr>
      <td> Card Expiration: </td>
      <td><%= "#{card.expiration_month}/#{card.expiration_year}" %> </td>
    </tr>

  </table>
</div>

app/views/cards/index.html.erb
<h2> <%= @header %> </h2>

<% @cards.each do |card| %>
  <%= render partial: 'card', locals: {card: card} %>
<% end %>
 

app/views/cards/new.html.erb
<div id = "new_card_container">

  <h2> Enter a new card to Wallet </h2>

  <%= form_for @card do |f| %>

    <p>
    <%= f.text_field :number, placeholder: "Credit Card Number",class: "formheight" %> </p>
    <p> <%= f.label :expiration_month %>
    <%= f.select :expiration_month, (1..12) %><br>
    <%= f.label :expiration_year %>
    <%= f.select :expiration_year, (2015..2029)%> </p>
    <p> <%= f.submit 'Submit', class: "formheight" %> </p>

  <% end %>

</div>


<%= render 'shared/errors', model: @card %>

<div id='client-side-error'> </div>

app/views/cards/show.html.erb
<div class=<%= "card #{@card.card_type.downcase.gsub(/\s/,'')}"%> >
  <ul class='card-attributes'>
    <li> <%= @card.card_type %> </li>
    <li> <%= @card.number %> </li>
    <li> Expires: <%= "#{@card.expiration_month}/#{@card.expiration_year}" %> </li>
  </ul>
</div>

<%= form_for :user_card, url: share_card_path do |f| %>
  <%= f.hidden_field :card_id, value: @card.id %>
  <%= f.select :user_id, User.all.map{ |u| [u.full_name, u.id] } %>
  <%= f.submit 'Add User to card' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>

    <title>Wallet</title>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

    <%= csrf_meta_tags %>

  </head>

  <body>

    <div id = "pagecontainer">

    <header>

      <div id = "alert">

        <%= render 'shared/flashes' %>
      
      </div>

      <h1>My Wallet </h1>

      <nav>

        <ul>

          <% if current_user %>

            <li> <%= link_to 'My Cards', user_cards_path(current_user) %> </li>
            <li> <%= link_to 'All Users', users_path %> </li>
            <li> <%= link_to 'All Cards', cards_path %> </li>
            <li> <%= link_to 'Create New Card', new_card_path %> </li>
            <li> <%= link_to "Logout #{current_user.fname}  ", session_path(current_user.id), method: :delete %> </li>

          <% elsif current_admin %>

            <li> <%= link_to 'All Cards', admin_cards_path %></li>
             <li> <%= link_to "Logout #{current_admin.username}  ", new_admin_session_path(current_admin.id), method: :delete %> </li>

          <% else %>

            <li> <%= link_to 'Admin Login', new_admin_session_path %> </li>
            <li> <%= link_to 'Login', root_path %> </li>
            <li> <%= link_to 'Sign Up', new_user_path %> </li>

          <% end %>
              
        </ul>

        <hr>

      </nav>


    </header>

    <%= yield %>

    </div>

  </body>

</html>

app/views/shared/_errors.html.erb
<% if model.errors.any? %>
  <ul>
    <% model.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_flashes.html.erb
<% if flash[:notice] %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div id = "edituserbox">

<h2> Edit User </h2>

<%= render 'shared/errors', model: @user %>

<%= form_for @user do |f| %>

  <p> First Name: <br>  
  <%= f.text_field :fname, placeholder: 'First Name', class: "formheight" %> </p>
  <p> Last Name: <br>
    <%= f.text_field :lname, placeholder: 'Last Name', class: "formheight" %></p>
  <p> Email Address: <br>
    <%= f.text_field :email, placeholder: 'Email', class: "formheight" %></p>
  <p> Phone Number: <br>
    <%= f.text_field :phone, placeholder: 'Phone', class: "formheight" %></p>
  <p> Password: <br>
    <%= f.password_field :password, placeholder: 'Password', class: "formheight" %></p>
  <p> Password Confirmation: <br>
    <%= f.password_field :password_confirmation, placeholder: 'Confirm password', class: "formheight" %></p>
  <p> <%= f.submit 'Edit', class: "formheight" %> </p>
  
<% end %>

<%= link_to "Delete Account", user_path(@user), method: :delete %>

</div>

app/views/users/index.html.erb
<h2> Card Users </h2>

<% @users.each do |user| %>
  <div>
    <p>
      <%= user.full_name %> <br>
      <%= user.email %> <br>
      <%= user.phone %> <br> <br>
      <%= link_to 'Cards', user_cards_path(user) %>
      <%= link_to 'Edit', edit_user_path(user) %>
    </p> <hr>

  </div>

<% end %>

app/views/users/new.html.erb
<div class = "alert">
  <%= render 'shared/errors', model: @user %>
</div>


<div id = "sign_up_box">
  <h2>Create an Account</h2>
  <%= form_for @user do |f| %>
    <p> <%= f.text_field :fname, placeholder: 'First Name', class: "formheight" %> </p> 
    <p> <%= f.text_field :lname, placeholder: 'Last Name', class: "formheight" %> </p> 
    <p> <%= f.text_field :email, placeholder: 'Email', class: "formheight" %> </p> 
    <p> <%= f.text_field :phone, placeholder: 'Phone', class: "formheight" %> </p> 
    <p> <%= f.password_field :password, placeholder: 'Password', class: "formheight" %> </p> 
    <p> <%= f.password_field :password_confirmation, placeholder: 'Confirm password', class: "formheight" %> </p> 
    <%= f.submit 'Submit', class: "loginbutton" %>
  <% end %>
</div>

app/views/users/show.html.erb
<h1> Show page for user </h1>
  <div>
    <%= @user.full_name %>
    <%= link_to 'Cards', user_cards_path(@user) %>
  </div>